### ISSUE TITLE
Lengthy words

### ISSUE THREAD

**Issue by olistik** [meh-42/playground#2]
Write a Ruby method that receives a sentence (a string) and returns the number of words in that sentence that are longer than 5 characters.

```ruby
def long_words_count(sentence)
  # TODO: implement me
end

sentence = "Nel ciel che più de la sua luce prende fu’ io e vidi cose che ridire né sa né può chi di là sù discende perché appressando sé al suo disire nostro intelletto si profonda tanto che dietro la memoria non può ire"

count = long_words_count(sentence)
puts "There are #{count} words longer than 5 characters"
```

## Step 2

Update the method to accept another input representing the length that will be used to count the words.

**Comment by olistik** [comment]
https://github.com/meh-42/playground/commit/f4dd498fd85ba38d645ba493d61513b03f396c26

**Comment by olistik** [comment]
@EnigmaEdivad Quando vuoi referenziare una issue all'interno del messaggio di un commit, usa questa la convenzione `#numero-issue`.

Ad esempio, se un commit riguarda la issue 23, allora nel messaggio commit potresti inserire `#23`.

**Comment by EnigmaEdivad** [comment]
Capito capito.

Il giorno sab 8 dic 2018, 15:04 olistik <notifications@github.com> ha
scritto:

**Comment by olistik** [comment]
@EnigmaEdivad A proposito, cosa ti ha stampato a schermo l'ultima versione del programma? 😄
