### ISSUE TITLE
Gotta chain'em all!

### ISSUE THREAD

**Issue by olistik** [meh-42/playground#4]
Riprendendo la issue #2 prova a riscrivere il metodo `long_word_counts` in modo che usi meno variabili temporanee possibile (come `list` e `selected`).

A scopo di esempio, ricorda che:

```ruby
n = 347
s = n.to_s
t = s.reverse
m = t.to_i
puts m
```

può essere riscritto come:

```ruby
x = 347.to_s.reverse.to_i
puts x
```

Recupera le ultime modifiche apportate nel repository con un `git pull` da linea di comando e crea il file `issue-4.rb`.

**Comment by EnigmaEdivad** [comment]
Dove trovo la linea di comando?

**Comment by olistik** [comment]
> Dove trovo la linea di comando?

È un altro nome per il "terminale" o "shell".

È quel programma dove di solito scrivi `atom .` per aprire l'editor di testo dalla cartella corrente.

**Comment by EnigmaEdivad** [comment]
Ah ok, il terminale. Adesso verifico se l'issue-4 è giusto e te lo pusho.

Il giorno sab 8 dic 2018, 15:51 olistik <notifications@github.com> ha
scritto:

**Comment by olistik** [comment]
@EnigmaEdivad Il commit https://github.com/meh-42/playground/commit/756b21d7b44ce8e7d147a4a9a5a43af5bb7b5b6d va nella direzione giusta, bravo. 👍 

C'è un ulteriore margine di miglioramento. Puoi concatenare anche il risultato di un blocco `do end`.
Riesci ad immaginare cosa potresti agganciare e dove?
